version: '3.9'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: firebudget
      MYSQL_USER: firebudget
      MYSQL_PASSWORD: firebudget
      MYSQL_DATABASE: firebudget
    ports:
      - '3307:3306'
    # volumes:
    # - ./.docker/database:/var/lib/mysql
